# En un template se accede vía {{ site.myvariable }} a cualquier valor definido aquí.
title: Desafíos Frontend
tab_title: Desafíos Frontend #This text shows up on the browser tab
email:
description: Desafíos de JavaScript, React y más
# url: "https://peahatlanding.github.io/Plain-Webcomic/" # the base hostname & protocol for your site

#twitter_username: http://twitter.com/peahat
#tumblr_username: http://peahat.tumblr.com
#patreon_username: peahat

# Author Social Media
author_twitter_username:
author_tumblr_username:
author_patreon_username:

# Almacenar las colecciones en un solo directorio
collections_dir: challenges
# Cada colección es iterable usando for
collections:
  js:
    output: true
    permalink: /:collection/:name/
  react:
    output: true
    permalink: /:collection/:name/

# Valores por defectos para las colecciones
defaults:
  - scope:
      path: ""
      type: js
    values:
      layout: reto
  - scope:
      path: ""
      type: react
    values:
      layout: reto

# habilitamos para trabajar con sass
sass:
  sass_dir: _sass
  style: compressed # (expanded | compressed)

# Build settings
markdown: kramdown
